### ISSUE TITLE
Implement protocol functions inside the main class

### ISSUE THREAD

**Issue by htinlinn** [prolificinteractive/simcoe#26]
Currently, protocol functions for Adobe and mParticle are implemented in extensions. The current Swift version disallows overriding functions that are implemented in extensions. 

> Declarations from extensions cannot be overridden yet

By moving the implementations to the main class and adding the `open` keyword, it will allow users to override them as needed.

**Comment by Haud** [comment]
IMO using inheritance to achieve polymorphic behavior is the wrong approach. Originally, I designed this with the idea that if you want to extend or change the default functionality, then you should roll your own and potentially encapsulate the base handlers for implementations that need it; this is why I rolled all classes as `final`. 

I think pushing this towards inheritance instead of composition is the wrong approach (and anti-Swift's protocol-oriented design)

**Comment by htinlinn** [comment]
Fair point. I was thinking about this from the point of view of a user rather than a designer of the framework. 

For my use case, I only needed to override one function and keep the implementations for all the other functions the same. For Adobe, it's fine since it only have a couple of functions anyways but for providers with more default implementations like mParticle, it would be kind of a hassle to have to implement all the protocol functions only to for forward the call to the base handler. 

Anyways, I do like your suggestion because it keeps things purer. @MichaelCampbell @yoyoyoseob what do you guys think?

PS: I don't think inheritance is totally against Swift's protocol-oriented design. After all, they added protocol extensions which is functionally similar to inheriting a function implementation from a parent class.

**Comment by Haud** [comment]
Yeah, I think the overhead of reimplementing everything can be a bit much, but it's also a one-time only thing and if you're already customizing one thing, the odds that you won't have to customize others are low (IMO). I think this allows the base implementation to clean and injectable in more scenarios. 

The idea of Simcoe too is that it should be able to handle multiple frameworks for analytics, so subclassing one framework exclusively would go against the grain ... if you change it later, you'll have to refactor it all.

**Comment by yoyoyoseob** [comment]
Closing this out with the merging of PR #27
