### ISSUE TITLE
mParticle README embedded when installing with Cocoapods

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/simcoe#40]
Hi,

I get a warning from Xcode when installing Simcoe mParticle subspec:

`Warning: no rule to process file '.../Pods/Simcoe/Simcoe/mParticle/README.md' of type net.daringfireball.markdown for architecture x86_64`

When I checked my Pods folder, I can indeed see that README.md from mParticle folder was added:

![screen shot 2017-05-17 at 5 17 50 pm](https://cloud.githubusercontent.com/assets/6641355/26176699/05e2b3c0-3b25-11e7-9815-db4be2239356.png)

Any chance you can fix this?

Thanks!

**Comment by yoyoyoseob** [comment]
Closing with the release of 1.1.0
