### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by sp71** [prolificinteractive/simcoe#8]
Currently, pod 'Simcoe' generates the following error on pod install,
[!] Unable to find a specification for `Simcoe`

Until this issue is resolved, simply add the following to Podfile
pod 'Simcoe', :git => 'https://github.com/prolificinteractive/simcoe'

**Comment by MichaelCampbell** [comment]
Hey @sp71, Simcoe has just been submitted to Cocoapods. Please retry and let me know if it works for you.

**Comment by sp71** [comment]
Works perfectly now
