### ISSUE TITLE
App Transport Remote Logging 

### ISSUE THREAD

**Issue by jgsamudio** [prolificinteractive/simcoe#9]
When Simcoe starts it automatically begins logging remotely. There should be an option to enable or disable remote logging. With App Transport enabled it will log in the debugger that it blocked the http request because it was not secure. The only other option is to add the remote url to the exception domain.

**Comment by MichaelCampbell** [comment]
@jgsamudio Please take a look at #11 and let me know if you have any questions. 

The output of the `RemoteOutput` can be toggled by changing the `OutputOptions` enum value in `Tracker` as demonstrated below, so there was no change made with this regard.

e.g., 

```
Simcoe.run()
Simcoe.engine.tracker.outputOption = .None
```
